var __v="\u003cpre class=\"k-pre\"\u003eexception bad_exception定义于\u0026lt;exception\u0026gt; \nbad_alloc定义于\u0026lt;new\u0026gt; \nbad_cost和bad_typeid定义于\u0026lt;typeinfo\u0026gt; \nios_base::failure定义于\u0026lt;ios\u0026gt; \n其他\u0026lt;stdexcept\u0026gt;\n\n\n对于所有被声明与某区段——而该区段因程序异常而退离得局部函数，其destructor会被调用\n\ntry\n{\n\tthrow value;//value 可以是任何型别\n}\ncatch(const value的型别 \u0026amp;)\n{\n\n}\n\n \nvoid test() throw (型别);//指明函数抛出的异常 [throw() 表明无异常抛出]\n\n标准异常可分为三组 1语言本身支持的 2c++标准库发出的 3程序作用域之外发出的\n\u003cimg src='/sections/1319/image/exception.png' style=\"max-width: 100%;\"\u003e\n\u003c/pre\u003e"